name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: Run linting
        run: golangci-lint run
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build
        run: go build -v ./...

  # This job will only succeed if all other jobs succeed
  all-checks:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: always()

    steps:
      - name: Check all jobs
        run: |
          if [[ "${{ needs.lint.result }}" != "success" ]]; then
            echo "❌ Linting failed"
            exit 1
          fi
          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "❌ Build failed"
            exit 1
          fi
          echo "✅ All checks passed!"

      - name: Comment on PR failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            let failedJobs = [];

            if ("${{ needs.lint.result }}" !== "success") failedJobs.push("Linting");
            if ("${{ needs.build.result }}" !== "success") failedJobs.push("Build");

            const failedJobsList = failedJobs.map(job => "- " + job).join("\n");

            const body = "❌ **CI Checks Failed**\n\n" +
                         "The following checks failed:\n" +
                         failedJobsList + "\n\n" +
                         "Please fix the issues before merging this PR.\n\n" +
                         "**Quick fixes:**\n" +
                         "- For linting issues: Run `make lint` locally\n" +
                         "- For test failures: Run `make test` locally\n" +
                         "- For build issues: Run `make build` locally";

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
