name: Release
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed
jobs:
  update-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.version }}
      should_release: ${{ steps.version.outputs.hasNextVersion }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: thenativeweb/get-next-version@main
        id: version
        with:
          tag_prefix: 'v'

  release:
    runs-on: ubuntu-latest
    needs: [update-version]
    permissions:
      contents: write
    if: needs.update-version.outputs.should_release == 'true'
    steps:
      - name: Generate release notes
        id: release-notes
        run: |
          LATEST_TAG="${{ needs.update-version.outputs.tag }}"

          # Get commits since last tag
          if [ "$LATEST_TAG" != "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" $LATEST_TAG..HEAD)
          else
            COMMITS=$(git log --pretty=format:"- %s (%h)")
          fi

          # Get contributors since last tag
          if [ "$LATEST_TAG" != "v0.0.0" ]; then
            CONTRIBUTORS=$(git log --pretty=format:"%an" $LATEST_TAG..HEAD | sort | uniq | sed 's/^/- /')
          else
            CONTRIBUTORS=$(git log --pretty=format:"%an" | sort | uniq | sed 's/^/- /')
          fi

          # Create release notes
          cat > release_notes.md << EOF
          ## Changes

          $COMMITS

          ## Contributors

          $CONTRIBUTORS
          EOF

          echo "release_notes_file=release_notes.md" >> $GITHUB_OUTPUT
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'release.tar.gz'
          name: 'Release ${{ needs.update-version.outputs.tag }}'
          tag: '${{ needs.update-version.outputs.tag }}'
          body_path: ${{ steps.release-notes.outputs.release_nodes.md }}
