version: "2"
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
      # Use stricter formatting than gofmt
      extra-rules: true

    goimports: {}
      # Put imports beginning with prefix after 3rd-party packages

    golines:
      # Target maximum line length
      max-len: 80
      # Length of a tabulation
      tab-len: 2
      # Shorten single-line comments
      shorten-comments: true
      reformat-tags: true
      # Split chained methods on the dots as opposed to the arguments
      chain-split-dots: true

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - funcorder
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - godox
    - gosec
    - grouper
    - iface
    - importas
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - tagalign
    - testableexamples
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - wrapcheck
  settings:
    gocritic:
      enable-all: true
    misspell:
      ignore-rules: []
    gosec:
      config:
        G302: "0644"
        G306: "0644"